[project]
name = "the-nitpicker"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "google-genai>=1.31.0",
    "mcp[cli]>=1.13.1",
    "requests>=2.32.5",
]
